# Generated by Django 2.1.2 on 2018-11-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tender_ID', models.IntegerField(db_column='Tender_ID')),
                ('ProcDt', models.DateTimeField(db_column='ProcDt')),
                ('TenderPrice', models.FloatField(db_column='TenderPrice', null=True)),
                ('StatusT_ID', models.IntegerField(db_column='StatusT_ID')),
                ('FormT_ID', models.IntegerField(db_column='FormT_ID')),
                ('ClaimDtBeg', models.DateTimeField(db_column='ClaimDtBeg', null=True)),
                ('TendSYSDATE', models.DateTimeField(db_column='TendSYSDATE')),
                ('Lot_ID', models.IntegerField(db_column='Lot_ID')),
                ('PlanTYear', models.IntegerField(db_column='PlanTYear', db_index=True, null=True)),
                ('InnNx', models.IntegerField(db_column='InnNx', db_index=True, null=True)),
                ('TradeNx', models.IntegerField(db_column='TradeNx', null=True)),
                ('Order_Price', models.FloatField(db_column='Order_Price', null=True)),
                ('Order_Count', models.IntegerField(db_column='Order_Count', null=True)),
                ('Order_Sum', models.FloatField(db_column='Order_Sum', null=True)),
                ('Ship_FinalPrice', models.FloatField(db_column='Ship_FinalPrice', null=True)),
                ('market_name', models.CharField(db_column='market_name', max_length=32, null=True)),
                ('market_id', models.IntegerField(db_column='market_id', db_index=True, null=True)),
            ],
            options={
                'db_table': 'Test_CACHE_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lpu',
            fields=[
                ('cust_id', models.IntegerField(db_column='Cust_ID', db_index=True, primary_key=True, serialize=False)),
                ('inn', models.CharField(db_column='Org_CustINN', db_index=True, max_length=12)),
                ('name', models.CharField(db_column='Org_CustNm', max_length=2000)),
            ],
            options={
                'db_table': 'db_lpu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketMnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnn_id', models.IntegerField(db_index=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Market')),
            ],
        ),
        migrations.CreateModel(
            name='MarketTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_id', models.IntegerField(db_index=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org'),
        ),
        migrations.AddField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org'),
        ),
        migrations.AddField(
            model_name='employee',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Employee'),
        ),
    ]
