# Generated by Django 2.1.2 on 2018-12-15 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InNR',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=300)),
            ],
            options={
                'db_table': 'db_innr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lpu',
            fields=[
                ('cust_id', models.IntegerField(db_column='Cust_ID', db_index=True, primary_key=True, serialize=False)),
                ('inn', models.CharField(db_column='Org_CustINN', db_index=True, max_length=16, verbose_name='ИНН')),
                ('name', models.CharField(db_column='Org_CustNm', db_index=True, max_length=512, verbose_name='Грузополучатель')),
                ('shortname', models.CharField(blank=True, db_column='shortname', max_length=512, null=True, verbose_name='Грузополучатель полное имя')),
                ('addr1', models.CharField(blank=True, db_column='addr1', max_length=512, null=True, verbose_name='Адрес1')),
                ('addr2', models.CharField(blank=True, db_column='addr2', max_length=512, null=True, verbose_name='Адрес2')),
                ('regcode', models.IntegerField(blank=True, db_column='regcode', null=True, verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Грузополучатель',
                'verbose_name_plural': 'Грузополучатели',
                'db_table': 'db_lpu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusT',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=40)),
            ],
            options={
                'db_table': 'db_statusT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradeNR',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=254)),
            ],
            options={
                'db_table': 'db_tradenr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WinnerOrg',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=512)),
                ('inn', models.CharField(blank=True, db_column='inn', max_length=16, null=True)),
            ],
            options={
                'db_table': 'db_WinnerOrg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Краткое имя')),
                ('istarget', models.BooleanField(db_index=True, default=True, verbose_name='Таргет')),
                ('lpu', models.ManyToManyField(blank=True, related_name='lpus', to='db.Lpu', verbose_name='Грузополучатели')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Рынок')),
                ('innrs', models.ManyToManyField(blank=True, to='db.InNR', verbose_name='МНН')),
            ],
            options={
                'verbose_name': 'Рынок',
                'verbose_name_plural': 'Рынки',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Организация')),
                ('sync_time', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Время синхронизации')),
                ('sync_flag', models.BooleanField(blank=True, default=False, verbose_name='Запустить формирование БД')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Логин входа')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Org_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=64, verbose_name='Сообщение')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org')),
            ],
            options={
                'verbose_name': 'Событие БД',
                'verbose_name_plural': 'События БД',
            },
        ),
        migrations.AddField(
            model_name='market',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='market',
            name='tmnrs',
            field=models.ManyToManyField(blank=True, to='db.TradeNR', verbose_name='Торговые наименования'),
        ),
        migrations.AddField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='employee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Employee', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='employee',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='employee_user', to=settings.AUTH_USER_MODEL, verbose_name='Логин входа'),
        ),
    ]
