# Generated by Django 2.1.2 on 2018-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.IntegerField(db_index=True)),
                ('entity', models.CharField(max_length=128)),
                ('employee', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
