# Generated by Django 2.1.2 on 2018-12-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='sync_status',
            field=models.BooleanField(blank=True, choices=[(0, 'БД в работе'), (1, 'БД обновляется'), (2, 'БД формируется'), (3, 'БД на обслуживании'), (4, 'Сбой БД')], default=0, verbose_name='Состояние синхронизации'),
        ),
    ]
