# Generated by Django 2.1.2 on 2018-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusT',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=40)),
            ],
            options={
                'db_table': 'db_statusT',
                'managed': False,
            },
        ),
    ]
