# Generated by Django 2.1.2 on 2018-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_statust'),
    ]

    operations = [
        migrations.CreateModel(
            name='InNR',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
            ],
            options={
                'db_table': 'db_inNR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradeNR',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
            ],
            options={
                'db_table': 'db_tradeNR',
                'managed': False,
            },
        ),
    ]
