# Generated by Django 2.1.2 on 2018-10-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_hs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hs',
            name='hs_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
