# Generated by Django 2.1.2 on 2018-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_innr_tradenr'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerOrg',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('inn', models.CharField(blank=True, db_column='inn', max_length=12, null=True)),
            ],
            options={
                'db_table': 'db_WinnerOrg',
                'managed': False,
            },
        ),
    ]
