# Generated by Django 2.1.2 on 2018-12-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20181224_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_log',
            name='description',
            field=models.CharField(max_length=128, verbose_name='Сообщение'),
        ),
    ]
