# Generated by Django 2.1.2 on 2018-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_hs_hs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hs',
            name='с_package_avg_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
