# Generated by Django 2.1.2 on 2018-10-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20181021_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hs',
            name='с_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
