# Generated by Django 2.1.2 on 2018-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_winnerorg'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
