# Generated by Django 2.1.2 on 2018-11-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_idlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmnn',
            name='mnn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.InNR'),
        ),
        migrations.AlterField(
            model_name='markettm',
            name='tm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.TradeNR'),
        ),
    ]
