# Generated by Django 2.1.2 on 2019-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_org_db_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.IntegerField(db_column='Reg_ID', db_index=True, primary_key=True, serialize=False)),
                ('regnm', models.CharField(db_column='RegNm', db_index=True, max_length=50, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'db_region',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='employee_regions', to='db.Region', verbose_name='Регионы'),
        ),
    ]
