# Generated by Django 2.1.2 on 2018-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20181021_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hs',
            name='inn_winner',
            field=models.CharField(blank=True, db_index=True, max_length=28, null=True),
        ),
    ]
