# Generated by Django 2.1.2 on 2019-01-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20190109_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_log',
            name='last_sync_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
