# Generated by Django 2.1.2 on 2018-10-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20181021_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hs',
            name='c_inn_shipper',
            field=models.CharField(blank=True, db_index=True, max_length=26, null=True),
        ),
    ]
