# Generated by Django 2.1.2 on 2018-11-11 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0007_hstemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='org',
            name='sync_time',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Время синхронизации'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Организация'),
        ),
    ]
