# Generated by Django 2.1.2 on 2019-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_org_log_last_sync_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_log',
            name='last_sync_dt',
        ),
        migrations.AddField(
            model_name='org',
            name='last_sync_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
