# Generated by Django 2.1.2 on 2018-10-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20181029_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmnn',
            name='mnn_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='markettm',
            name='tm_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
