# Generated by Django 2.1.5 on 2019-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
