# Generated by Django 2.1.2 on 2018-11-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20181112_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Employee', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Логин входа'),
        ),
    ]
