# Generated by Django 2.1.2 on 2018-10-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20181029_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lpu',
            options={'managed': False},
        ),
    ]
