# Generated by Django 2.1.5 on 2019-04-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20190414_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filters',
            old_name='folters_json',
            new_name='filters_json',
        ),
    ]
