# Generated by Django 2.1.2 on 2018-11-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20181113_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notarget',
            field=models.BooleanField(default=False, verbose_name='Не показывать как Таргет'),
        ),
    ]
