# Generated by Django 2.1.2 on 2018-11-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20181113_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Employee', verbose_name='Руководитель'),
        ),
    ]
