# Generated by Django 2.1.5 on 2019-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190414_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='xls_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
