# Generated by Django 2.1.2 on 2018-10-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20181030_1329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hs',
            table='Test_CACHE_1',
        ),
    ]
