# Generated by Django 2.1.2 on 2018-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20181113_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='notarget',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Не Таргет'),
        ),
    ]
