# Generated by Django 2.1.2 on 2018-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20181113_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='notarget',
        ),
        migrations.AddField(
            model_name='employee',
            name='istarget',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Таргет'),
        ),
    ]
