# Generated by Django 2.1.2 on 2018-10-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20181030_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lpu',
            table='db_lpu',
        ),
    ]
