# Generated by Django 2.1.2 on 2018-11-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20181113_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Рынок', 'verbose_name_plural': 'Рынки'},
        ),
        migrations.AddField(
            model_name='market',
            name='innr',
            field=models.ManyToManyField(through='db.MarketMnn', to='db.InNR', verbose_name='МНН'),
        ),
        migrations.AddField(
            model_name='market',
            name='tmnr',
            field=models.ManyToManyField(through='db.MarketTM', to='db.TradeNR', verbose_name='Торговые наименования'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Рынок'),
        ),
        migrations.AlterField(
            model_name='market',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org', verbose_name='Организация'),
        ),
    ]
