# Generated by Django 2.1.5 on 2019-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=40)),
                ('shortname', models.CharField(db_column='shortname', max_length=40)),
            ],
            options={
                'db_table': 'db_unit',
                'managed': False,
            },
        ),
    ]
