# Generated by Django 2.1.2 on 2018-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20181113_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='innr',
        ),
        migrations.RemoveField(
            model_name='market',
            name='tmnr',
        ),
        migrations.AddField(
            model_name='market',
            name='innrs',
            field=models.ManyToManyField(to='db.InNR', verbose_name='МНН'),
        ),
        migrations.AddField(
            model_name='market',
            name='tmnrs',
            field=models.ManyToManyField(to='db.TradeNR', verbose_name='Торговые наименования'),
        ),
    ]
