# Generated by Django 2.1.2 on 2018-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20181113_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketmnn',
            name='market',
        ),
        migrations.RemoveField(
            model_name='marketmnn',
            name='mnn_id',
        ),
        migrations.RemoveField(
            model_name='markettm',
            name='market',
        ),
        migrations.RemoveField(
            model_name='markettm',
            name='tm_id',
        ),
        migrations.AlterField(
            model_name='market',
            name='innrs',
            field=models.ManyToManyField(blank=True, to='db.InNR', verbose_name='МНН'),
        ),
        migrations.AlterField(
            model_name='market',
            name='tmnrs',
            field=models.ManyToManyField(blank=True, to='db.TradeNR', verbose_name='Торговые наименования'),
        ),
        migrations.DeleteModel(
            name='MarketMnn',
        ),
        migrations.DeleteModel(
            name='MarketTM',
        ),
    ]
