# Generated by Django 2.1.5 on 2019-05-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_formt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BProg',
            fields=[
                ('id', models.IntegerField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
            ],
            options={
                'db_table': 'db_bprog',
                'managed': False,
            },
        ),
    ]
