# Generated by Django 2.1.2 on 2018-11-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20181113_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lpu',
            field=models.ManyToManyField(related_name='lpus', to='db.Lpu'),
        ),
    ]
