# Generated by Django 2.1.5 on 2019-05-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_bprog'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='sendmail_create',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filters',
            name='sendmail_shedule',
            field=models.IntegerField(default=0),
        ),
    ]
