# Generated by Django 2.1.2 on 2018-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_employee_lpu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpu',
            options={'managed': False, 'verbose_name': 'Грузополучатель', 'verbose_name_plural': 'Грузополучатели'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='lpu',
            field=models.ManyToManyField(related_name='lpus', to='db.Lpu', verbose_name='Грузополучатели'),
        ),
    ]
