# Generated by Django 2.1.2 on 2018-11-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_auto_20181113_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Target',
        ),
    ]
