# Generated by Django 2.1.2 on 2018-11-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20181115_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, verbose_name='События БД')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Org')),
            ],
            options={
                'verbose_name': 'Событие БД',
                'verbose_name_plural': 'События БД',
            },
        ),
    ]
