# Generated by Django 2.1.2 on 2018-11-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_org_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_log',
            name='description',
            field=models.CharField(max_length=64, verbose_name='Сообщение'),
        ),
    ]
