# Generated by Django 2.1.2 on 2018-11-15 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20181115_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_log',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
