# Generated by Django 2.1.2 on 2018-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_org_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='sync_flag',
            field=models.BooleanField(blank=True, default=False, verbose_name='Запустить формирование БД'),
        ),
    ]
