# Generated by Django 2.1.2 on 2018-12-09 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20181203_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='orgs', to=settings.AUTH_USER_MODEL, verbose_name='Логин входа'),
        ),
    ]
