# Generated by Django 2.1.2 on 2018-12-09 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_auto_20181209_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Логин входа'),
        ),
    ]
