# Generated by Django 2.1.2 on 2018-12-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20181209_1635'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='innr',
            table='db_innr',
        ),
        migrations.AlterModelTable(
            name='tradenr',
            table='db_tradenr',
        ),
    ]
