# Generated by Django 2.1.2 on 2018-12-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isorgadmin',
            new_name='is_orgadmin',
        ),
    ]
