ft_unknown = -1
ft_none    = 0
ft_integer = 1
ft_numeric = 2
ft_date    = 3
ft_string  = 4
ft_fk      = 5

cache_unknown  = 0
cache_tender   = 1
cache_contract = 2

gr_1 = 'Group1'

cache_metadata = {
#    'fname' : {'title' : 'fieldtitle', 'type' : ft_fk, 'fk' : 'foreignkey_ref', 'cache' : cache_tender, 'group' : gr_1},
'PublDt' : { 'title' : 'Дата публикации', 'type' : ft_date, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'TendDt' : { 'title' : 'Дата проведения торгов', 'type' : ft_date, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'NotifNr' : { 'title' : 'Номер извещения', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'FZ_FK' : { 'title' : 'ФЗ', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'SrcInf' : { 'title' : 'Ссылка на извещение', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'TendNm' : { 'title' : 'Наименование торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'TenderPrice' : { 'title' : 'Начальная (максимальная) цена торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'SmallBusiness' : { 'title' : 'Торги для МБ', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'StatusT_Name' : { 'title' : 'Статус торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'FormT_Name' : { 'title' : 'Форма торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'FONm' : { 'title' : 'Федеральный округ проведения торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'RegNm' : { 'title' : 'Регион проведения торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'City_Name' : { 'title' : 'Населенный пункт', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Org_CustINN' : { 'title' : 'ИНН заказчика торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Org_CustNm' : { 'title' : 'Заказчик торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Org_SubCustINN' : { 'title' : 'ИНН уполномоченной организации', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Org_SubCustNm' : { 'title' : 'Уполномоченная организация', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Org_ProviderINN' : { 'title' : 'ИНН организатора торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Org_ProviderNm' : { 'title' : 'Организатор торгов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'ClaimReglament' : { 'title' : 'Место подачи заявок', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ClaimDtBeg' : { 'title' : 'Дата начала подачи заявок', 'type' : ft_date, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'ClaimDtEnd' : { 'title' : 'Дата окончания подачи заявок', 'type' : ft_date, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'Budgets_Name' : { 'title' : 'Тип бюджета', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'TenderDocReglament' : { 'title' : 'Источник финансирования', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PaymentReglament' : { 'title' : 'Порядок оплаты поставок товаров', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Tender_Lot' : { 'title' : 'Количество лотов', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Planned' : { 'title' : 'Наличие плана-графика', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PrefRus' : { 'title' : 'Преимущества для ТС', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'BudgetProg_Name' : { 'title' : 'Программа финансирования', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'LotNr' : { 'title' : 'Номер лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'LotStat' : { 'title' : 'Статус лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ReasonFailure' : { 'title' : 'Комментарии к статусу Лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'LotNm' : { 'title' : 'Наименование лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'SpecCount' : { 'title' : 'Количество позиций в спецификации', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'LFONm' : { 'title' : 'Федеральный округ поставки лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'LotRegNm' : { 'title' : 'Регион поставки лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PriceStart' : { 'title' : 'Начальная (максимальная) цена лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ConsigneeNm' : { 'title' : 'Грузополучатель', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ConsigneeInfo' : { 'title' : 'Сведения о грузополучателе', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PlanTName' : { 'title' : 'Период поставки', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PlanTYear' : { 'title' : 'Год поставки', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'PlanTVal' : { 'title' : 'Условия поставки', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'SupplyDt' : { 'title' : 'Срок действия контракта', 'type' : ft_date, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'ContrExpVal' : { 'title' : 'Примечание к сроку действия контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ClaimObesp' : { 'title' : 'Размер обеспечения заявки', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContrObesp' : { 'title' : 'Размер обеспечения контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'MonoMNN' : { 'title' : 'Монопозиционный (по МНН) лот', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'SupplierGroup_Name' : { 'title' : 'Группа поставщиков', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'WinnerOrgINN' : { 'title' : 'ИНН победителя по протоколу', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'WinnerOrg' : { 'title' : 'Победитель по протоколу', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'WinnerInfo' : { 'title' : 'Сведения о победителе по протоколу', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PriceMax' : { 'title' : 'Цена победителя по протоколу', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'SecondOrgINN' : { 'title' : 'ИНН второго участника лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'SecondOrgNm' : { 'title' : 'Второй участник лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'SecordOrgInfo' : { 'title' : 'Сведения о втором участнике лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PriceOther' : { 'title' : 'Цена второго участника лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ThirdOrgINN' : { 'title' : 'ИНН третьего участника лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ThirdOrgNm' : { 'title' : 'Третий участник лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ThirdOrgInfo' : { 'title' : 'Сведения о третьем участнике лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PriceThird' : { 'title' : 'Цена третьего участника лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'FourthOrgINN' : { 'title' : 'ИНН четвертого участника лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'FourthOrgNm' : { 'title' : 'Четвертый участник лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'FourthOrgInfo' : { 'title' : 'Сведения о четвертом участнике лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PriceFourth' : { 'title' : 'Цена четвертого участника лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'LotSpec_Pos' : { 'title' : 'Позиция в спецификации', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Innr' : { 'title' : 'МНН', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'TradeNmR' : { 'title' : 'ТН', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ProdNm' : { 'title' : 'Наименование позиции в спецификации', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Form' : { 'title' : 'Характеристика товара', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ShortName' : { 'title' : 'Единица измерения', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Price' : { 'title' : 'Начальная цена позиции в спецификации', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Num' : { 'title' : 'Количество по позиции в спецификации', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Summa' : { 'title' : 'Сумма по позиции в спецификации', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ATCID' : { 'title' : 'Классификатор лекарства', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractNr' : { 'title' : 'Реестровый номер контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractURL' : { 'title' : 'Ссылка на контракт', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractDate' : { 'title' : 'Дата подписания контракта', 'type' : ft_date, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'ContractPrice' : { 'title' : 'Цена контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractItemNm' : { 'title' : 'Наименование позиции контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'IntlName' : { 'title' : 'МНН контракт', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'TradeName' : { 'title' : 'ТН контракт', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ItemForma' : { 'title' : 'Характеристика позиции контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractItemUnit' : { 'title' : 'Единица измерения по контракту', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractItemPrice' : { 'title' : 'Цена позиции контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractItemCount' : { 'title' : 'Количество по позиции контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'ContractItemSum' : { 'title' : 'Сумма по позиции контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'VendorName' : { 'title' : 'Производитель/страна позиции контракта', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_InnR' : { 'title' : 'МНН (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_TradeNmR' : { 'title' : 'ТН (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Form' : { 'title' : 'Лекарственная форма полная (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Dosage' : { 'title' : 'Дозировка (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Package' : { 'title' : 'Первичная упаковка (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_PrimSize' : { 'title' : 'Объем (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_BatchSize' : { 'title' : 'Количество в потребительской упаковке (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Vendor' : { 'title' : 'Производитель ЛС (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Descr' : { 'title' : 'Полная характеристика ЛС (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Unit' : { 'title' : 'Единица измерения (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Price' : { 'title' : 'Начальная цена позиции (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_Count' : { 'title' : 'Количество по позиции (заказ)', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'Order_Sum' : { 'title' : 'Сумма по позиции (заказ)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Order_AVG_Price' : { 'title' : 'Средняя цена', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Form' : { 'title' : 'Лекарственная форма (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Dosage' : { 'title' : 'Дозировка (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Volume' : { 'title' : 'Объем (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_PrimSize' : { 'title' : 'Первичная упаковка (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_BatchSize' : { 'title' : 'Количество в потребительской упаковке (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Vendor' : { 'title' : 'Производитель ЛС (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Descr' : { 'title' : 'Полная характеристика ЛС (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Unit' : { 'title' : 'Единица измерения (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Price' : { 'title' : 'Цена позиции (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Count' : { 'title' : 'Количество по позиции (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_Sum' : { 'title' : 'Сумма по позиции (поставка)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Ship_FinalPrice' : { 'title' : 'Конечная цена лота', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'PriceDropPercentage' : { 'title' : 'Изменение цены лота (НМЦ/цена Победителя)', 'type' : ft_string, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}, 
'Item_ID' : { 'title' : 'ID Позиции', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'Tender_ID' : { 'title' : 'ID извещения', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'Contract_ID' : { 'title' : 'ID Контракта', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'Lot_ID' : { 'title' : 'ID лота', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1},
'LotSpec_ID' : { 'title' : 'ID спецификации', 'type' : ft_integer, 'fk' : '', 'cache' : cache_tender, 'group' : gr_1}
}